services:
  payments-db:
    image: postgres:15
    container_name: orbita-market-db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payments_db
    ports:
      - "5432:5432"
    networks:
      - orbita-market-net
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  payments-service:
    build:
      context: ./payments-service
      dockerfile: Dockerfile
    container_name: payments
    depends_on:
      payments-db:
        condition: service_healthy
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=docker
      - DB_HOST=payments-db
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    ports:
      - "8080:8080"
    networks:
      - orbita-market-net
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  orbita-market-net:
    driver: bridge
    name: orbita-market-net
